/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matth' at '22.09.17 11:48' with Gradle 2.14.1
 *
 * @author matth, @date 22.09.17 11:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
